name: 'Configuration Entity View'
description: 'Views handler implementation for configuration entities.'
# core: 8.x
type: module
package: Views
dependencies:
  - drupal:views

# Information added by Drupal.org packaging script on 2017-05-08
version: '8.x-1.0-alpha2'
core: '8.x'
project: 'config_views'
datestamp: 1494247839
